# This file was generated by GoReleaser. DO NOT EDIT.
cask "tronador-cli" do
  version "0.2.9-dependabot-go-modules-all-dependencies-fd0267bf8d.3"

  on_macos do
    on_intel do
      sha256 "5b193cf78229a7a918b7a6611db32e4b86131d73fa21202bc0c6fe8856bf00e8"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "d5eeb8a7c6b6a3a5e5d2eb65bc89ce286e4188bffe50651c3867ee4a9ac70cf7"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "4dda9f1357a3f470376e4978bc47c45a23adcc2dfae5d4f78f10d219a00dbc45"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "2aee17db92d93e9e67ea1797de7780a48ebe46be3f0ce6e89137b79181b5e5e6"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_arm64.zip"
    end
  end

  name "tronador-cli"
  desc "CLI tool for CloudOps Works Tronador workflows and AWS automation"
  homepage "https://github.com/cloudopsworks/tronador-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tronador"

  # No zap stanza required

end
