# This file was generated by GoReleaser. DO NOT EDIT.
cask "tronador-cli" do
  version "0.1.23"

  on_macos do
    on_intel do
      sha256 "af8e1e6a1861126e52c7d085671e68dbb78cf5b20295f6973c0708941ba95b22"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "881f88e3f76fdba1fd2a1c769c98031a00e2183208f730359990f8febe170102"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "a26aa9a1c4ec172b4612ca67fedf8d353c553af5a9688a7a51998ebc450b4527"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "d200e0e82a2b1097ab2b2e196eb6c3d172a2c1bc376703948942634e11a1a0a0"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_arm64.zip"
    end
  end

  name "tronador-cli"
  desc "CLI tool for CloudOps Works Tronador workflows and AWS automation."
  homepage "https://github.com/cloudopsworks/tronador-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tronador"

  # No zap stanza required

end
