# This file was generated by GoReleaser. DO NOT EDIT.
cask "tronador-cli" do
  version "0.1.6"

  on_macos do
    on_intel do
      sha256 "e82dd88e307fdcc9ceed3e501e7cbeff68b589706420a0399ec9df3b5ae58f66"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_amd64.zip"
    end
    on_arm do
      sha256 "d1807c874b197bc85f7f5e823e9351b8ac2a56db2460565e43fbfd8aae67deee"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "0a0949dd108a2e8091b3f9b989ae1e2442c5c89d15165cf0487932910e1ef9a0"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_amd64.zip"
    end
    on_arm do
      sha256 "93416a45cf0e0374858212635d713c667609c1141ec0af95596efdad155278d2"
      url "https://github.com/cloudopsworks/tronador-cli/releases/download/v#{version}/tronador-cli_#{version}_linux_arm64.zip"
    end
  end

  name "tronador-cli"
  desc "CLI tool for CloudOps Works Tronador workflows and AWS automation."
  homepage "https://github.com/cloudopsworks/tronador-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tronador"

  # No zap stanza required

end
